# Generated by Django 5.0 on 2025-12-10 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_old_columns'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_google_uid_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number with country code (e.g., +1234567890)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{1,14}$', 'Enter a valid phone number with country code (E.164 format)')]),
        ),
    ]
