# Generated by Django 5.0 on 2025-11-19 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='providerportfolio',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='categories',
            field=models.ManyToManyField(related_name='providers', to='providers.servicecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='provideravailability',
            unique_together={('provider', 'day_of_week', 'start_time')},
        ),
    ]
